@startuml


    class Tarea {
        - Integer id
        - String namTarea
        - String descripcion
        - Date fecha_creacion
        + getId(): Integer
        + setId(id: Integer): void
        + getNamTarea(): String
        + setNamTarea(namTarea: String): void
        + getDescripcion(): String
        + setDescripcion(descripcion: String): void
        + getFecha_creacion(): Date
        + setFecha_creacion(fecha_creacion: Date): void
    }




    class TareaController {
        + getAllTareas(): List<Tarea>
        + createTarea(tarea: Tarea): Tarea
    }




    class TareaService {
        + getTareas(): List<Tarea>
    }
    class TareaServiceImpl {
        + getTareas(): List<Tarea>
    }




    interface TareaRepository {
        + findAll(): List<Tarea>
    }


Tarea --> TareaRepository
TareaService <|-- TareaServiceImpl
TareaController --> Tarea
TareaServiceImpl ..> TareaRepository : utiliza

@enduml
