@startuml

package "controller" {
    [TareaController]
    [UsuarioRestController]
}

package "service" {
    package "Interfaces" {
        [IUsuarioService]
        [TareaService]
    }
    package "Implementaciones" {
        [TareaServiceImpl]
        [UsuarioServiceImpl]
    }
}

package "repository" {
    [IUsuarioRepository]
    [TareaRepository]
}

package "entity" {
    [Tarea]
    [Usuario]
}

package "exeption" {
    [ErrorDetails]
    [GlobalExceptionHandler]
    [ResourceNotFoundException]
}

controller --> service : utiliza
service --> repository : utiliza
service --> entity : maneja
controller --> exeption : maneja excepciones
exeption --> service : lanza excepciones

@enduml
